### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by amyamyx** [amyamyx/Slack-c#9]
- [x] BE routes
- [x] Create controllers
   - [x] Teams
   - [x] TeamMemberships
   - [x] Channels
   - [x] ChannelMessages
   - [x] ChannelMemberships
   - [x] Directs
   - [x] DirectMessages
   - [x] DirectMemberships
- [x] Add `visibility` column for `direct_memberships` table
- [x]  logout btn on main_page
- [x] Create JSON views
   - [x] Teams
   - [x] TeamMemberships
   - [x] Channels
   - [x] ChannelMessages
   - [x] ChannelMemberships
   - [x] Directs
   - [x] DirectMessages
   - [x] DirectMemberships
